services:
    php:
        build:
            context: .
            dockerfile: Dockerfile-php
        container_name: php_container
        volumes:
            - ./:/var/www
        ports:
            - "8000:8000"
        depends_on:
            - node

    node:
        build:
            context: .
            dockerfile: Dockerfile-node
        container_name: node_container
        volumes:
            - ./:/var/www
        ports:
            - "5173:5173"

    redis:
        image: redis:latest
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
