services:
    app:
        build: .
        container_name: laravel_app
        volumes:
            - .:/var/www
        ports:
            - "8000:8000"  # Laravel backend
            - "5173:5173"  # Vite frontend
        depends_on:
            - redis
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - REDIS_HOST=redis
            - DB_CONNECTION=sqlite
            - DB_DATABASE=/var/www/database/database.sqlite

    redis:
        image: redis:latest
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
